#!/bin/sh
#
# dmenu-edit: Use dmenu to open and edit a file from a given list.
#
# Copyright 2010 Tom Vincent <http://www.tlvince.com/>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# Global variables:
FILES="edit-list"       # Defaults to "$HOME/.config/dmenu-tools/edit-list"
TERMINAL="urxvtc"
WD="$(dirname "$(readlink -f "$0")")"

# Imports:
. "$WD/lib/logging.sh"

##
# Check to see if EDITOR has been set, otherwise read in.
#
isSet()
{
    if [[ -z $EDITORa ]]; then
        warn "\$EDITOR has not been set"
        info "Please enter the command of your file editor of choice:"
        read EDITORa
        isSet   # Double check
    fi
}

# Environment:
if [[ ! -d "${XDG_CONFIG_HOME:-"$HOME/.config"}/dmenu-tools" ]]; then
    mkdir -p "${XDG_CONFIG_HOME:-"$HOME/.config"}/dmenu-tools"
fi

# If not launched in a tty (e.g. using dmenu), open one up:
tty -s || $TERMINAL -e "$0" # XXX: terminal keeps closing
choice="$(dmenu < "$HOME/.config/dmenu-tools/edit-list")"
if [[ $choice ]]; then
    isSet
    $EDITORa "$HOME/$choice"
fi
