#!/bin/sh
#
# dmenu-menu: A recursive dmenu menu.
#
# Copyright 2010 Tom Vincent <http://www.tlvince.com/>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# Global variables:
CANONICAL="$(readlink -f "$0")"
BASE="$(dirname "$CANONICAL")"
HIDE="$XDG_CONFIG_HOME/dmenu/menu-hide"

choice="$(ls $BASE/dmenu-* | grep -vf "$HIDE" | \
            sed -e "s|$BASE/||g" -e "/${CANONICAL##*/}/d" | dmenu)"
[[ $choice ]] && exec "$BASE/$choice"
