#!/bin/sh
# dmenu-menu: A recursive dmenu menu.
# Copyright 2010-2011 Tom Vincent <http://www.tlvince.com/>

# Global variables:
CANONICAL="$(readlink -f "$0")"
BASE="$(dirname "$CANONICAL")"
PREFIX="dmenu-"

PATTERNS="
    s|$BASE/||g
    /${CANONICAL##*/}/d
    /^${PREFIX}path$/d
    s/$PREFIX//g
"

choice="$(ls ${BASE}/${PREFIX}* | sed -e "$PATTERNS" | dmenu)"
[[ $choice ]] && exec "$BASE/${PREFIX}$choice"
