#!/bin/sh
#
# Specify some defaults for dmenu.
#
# If programs want to override this, make sure they use the full path to dmenu
# (usr/bin/dmenu).

# Colours:
NORM_BG="#101010"
NORM_FG="#777777"
SELC_BG="#000000"
SELC_FG="#ffffff"
FONT="-*-terminus-medium-r-*-*-*-*-*-*-*-*-*-*"
/usr/bin/dmenu -i -nb $NORM_BG -nf $NORM_FG -sb $SELC_BG -sf $SELC_FG -fn $FONT ${1+"$@"}
