#!/bin/sh
# A recursive dmenu menu.
# Copyright 2010-2012 Tom Vincent <http://tlvince.com/contact>

# Global variables:
CANONICAL="$(readlink -f "$0")"
BASE="$(dirname "$CANONICAL")"
PREFIX="dmenu-"
CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/dmenu/dmenu.conf"
[ -f "$CONFIG" ] && source "$CONFIG"

PATTERNS="
    s|$BASE/||g
    /${CANONICAL##*/}/d
    /^${PREFIX}path$/d
    s/$PREFIX//g
"

choice="$(ls ${BASE}/${PREFIX}* | sed -e "$PATTERNS" | dmenu $DMENU_OPTS)"
[[ $choice ]] && exec "$BASE/${PREFIX}$choice"
