// Generated by CoffeeScript 1.4.0
(function() {

  $(function() {
    var MutationObserver, api, getReadme, getScripts, observer;
    api = 'https://api.github.com/repos/tlvince/dmenu-tools';
    getReadme = function() {
      return $.getJSON("" + api + "/readme?callback=?", function(response) {
        var html, readme;
        if (response.data.content) {
          if (response.data.encoding === 'base64') {
            readme = response.data.content.replace(/\n/g, '');
            readme = window.atob(readme);
            html = new Markdown.Converter().makeHtml(readme);
            return $('#main_content p').replaceWith(html);
          }
        }
      });
    };
    getScripts = function() {
      return $.getJSON("" + api + "/contents/src?callback=?", function(response) {
        var html, scripts, source, template;
        if (response.data) {
          source = $('#script-template').html();
          template = Handlebars.compile(source);
          scripts = {
            script: response.data
          };
          html = template(scripts);
          return $('#main_content h2').first().before(html);
        }
      });
    };
    getReadme();
    MutationObserver = window.MutationObserver || window.WebKitMutationObserver;
    observer = new MutationObserver(function(mutations) {
      getScripts();
      return observer.disconnect();
    });
    return observer.observe($('#main_content')[0], {
      childList: true
    });
  });

}).call(this);
