#!/bin/sh
# Switch netctl network profiles.
# Copyright 2013 Tom Vincent <http://tlvince.com/contact>

profile="$(netctl list | cut -c 3- | dmenu "$@")"
[ "$profile" ] && sudo netctl switch-to "$profile" &
