#!/bin/sh
# A recursive dmenu menu.
# Copyright 2010-2012 Tom Vincent <http://tlvince.com/contact/>

CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/dmenu_run"
CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/dmenu/dmenu.conf"

[ -f "$CACHE" ] || exit 1
[ -f "$CONFIG" ] && source "$CONFIG"

prefix="dmenu-"
choice="$(grep "$prefix" "$CACHE" | egrep -v "path|-menu" | \
          sed "s/$prefix//" | dmenu $DMENU_OPTS)"
[ $choice ] && exec "${prefix}$choice"
