#!/bin/sh
# Use dmenu to open and edit a file from a given list.
# Copyright 2010-2013 Tom Vincent <http://tlvince.com/contact/>

LOCAL="${LOCAL:-${XDG_LOCAL_HOME:-$HOME/.local/share}/dmenu/edit.txt}"
[ -f "$LOCAL" ] || exit 1

file="$(dmenu "$@" < "$LOCAL")"
[ "$file" ] && "${SHELL:-/bin/sh}" -c "$TERMINAL -e $EDITOR \"$file\" &" &
