#!/bin/sh
# Use dmenu to open and edit a file from a given list.
# Copyright 2010-2012 Tom Vincent <http://tlvince.com/contact/>

LOCAL="${XDG_LOCAL_HOME:-$HOME/.local/share}/dmenu-tools/edit.txt"
CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/dmenu-tools/dmenu-tools.conf"

[ -f "$LOCAL" ] || exit 1
[ -f "$CONFIG" ] && source "$CONFIG"

choice="$(dmenu $DMENU_OPTS < "$LOCAL")"
[ $choice ] && ${SHELL:-sh} -c "$TERMINAL -e $EDITOR \"$choice\" &" &
