#!/bin/sh
# Switch netcfg network profiles.
# Copyright 2010-2012 Tom Vincent <http://tlvince.com/contact/>

CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/dmenu/dmenu.conf"
NETCFG="/etc/network.d"

[ -f "$CONFIG" ] && . "$CONFIG"

cmd="$(find /etc/network.d -maxdepth 1 -type f -printf "%f\n" | \
          dmenu $DMENU_OPTS)"

[ "$cmd" ] && ${SHELL:-/bin/sh} -c "$TERMINAL -e sh -c \
  \"sudo netcfg -a && sudo netcfg \"$cmd\"\" &" &
