#!/bin/sh
# Sort dmenu items by usage. Append ";" to launch the app in terminal.
# Copyright 2009-2012 Tom Vincent <http://tlvince.com/contact/>

CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/dmenu-tools"
mkdir -p "$CACHE"
CACHE+="/dmenu-cache-recent.txt"
touch $CACHE

CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/dmenu-tools/dmenu-tools.conf"
[ -f "$CONFIG" ] && source "$CONFIG"

MOST_USED=$(sort $CACHE | uniq -c | sort -r | colrm 1 8)
RUN=$((echo "$MOST_USED"; dmenu-path | grep -vxF "$MOST_USED") | dmenu $DMENU_OPTS) &&
(echo $RUN; head -n 99 $CACHE) > $CACHE.$$ &&
mv $CACHE.$$ $CACHE

case $RUN in
    *\;) exec $(echo $TERMINAL -e ${RUN/;/});;
    *)   exec $RUN;;
esac
