#!/bin/sh
# Raise a command's window if it exists, otherwise run it.
# Copyright 2013 Tom Vincent <http://tlvince.com/contact/>

cmd="$(dmenu_path | dmenu "$@")"
[ "$cmd" ] && { wmctrl -a "$cmd" || ${SHELL:-"/bin/sh"} -c "$cmd &" & }
