#!/bin/sh
# Switch netcfg network profiles.
# Copyright 2010-2012 Tom Vincent <http://tlvince.com/contact/>

CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/dmenu-tools/dmenu-tools.conf"
NETCFG="/etc/network.d"

[ -f "$CONFIG" ] && source "$CONFIG"

choice="$(find /etc/network.d -maxdepth 1 -type f -printf "%f\n" | \
          dmenu $DMENU_OPTS)"

[ "$choice" ] && ${SHELL:-/bin/sh} -c "$TERMINAL -e sh -c \
  \"sudo netcfg -a && sudo netcfg \"$choice\"\" &" &
