#!/bin/sh
# A recursive dmenu menu.
# Copyright 2010-2012 Tom Vincent <http://tlvince.com/contact/>

CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/dmenu-tools/dmenu-cache.txt"
CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/dmenu-tools/dmenu-tools.conf"

[ -f "$CACHE" ] || exit 1
[ -f "$CONFIG" ] && source "$CONFIG"

choice="$(grep "dmenu-" "$CACHE" | egrep -v "path|-menu" | dmenu $DMENU_OPTS)"
[ $choice ] && exec "$choice"
